"""Cross-validation against the cryptography library as a reference implementation.

Two directions are tested. First, the reference library encrypts and our
implementation decrypts. Second, our implementation encrypts and the reference
library decrypts. Both passing together confirms that our key generation, OAEP
padding, MGF1, and RSA primitives agree with RFC 8017 as implemented by a
widely used, audited library.

The cryptography package is a test-only dependency and is never imported from src/.
"""

import pytest

cryptography = pytest.importorskip("cryptography")

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.hazmat.primitives.asymmetric.rsa import (
    RSAPrivateNumbers,
    RSAPublicNumbers,
)

from rsa_oaep.number_theory import generate_prime, modinv
from rsa_oaep.rsa import PrivateKey, PublicKey
from rsa_oaep.rsaes_oaep import decrypt, encrypt


OAEP_SHA256 = padding.OAEP(
    mgf=padding.MGF1(algorithm=hashes.SHA256()),
    algorithm=hashes.SHA256(),
    label=None,
)


def _generate_keypair_with_factors(bits: int = 2048, e: int = 65537):
    """Generate a keypair and also return p and q so a reference private key can be built."""
    half = bits // 2
    while True:
        p = generate_prime(half)
        q = generate_prime(half)
        if p == q:
            continue
        n = p * q
        if n.bit_length() != bits:
            continue
        phi = (p - 1) * (q - 1)
        try:
            d = modinv(e, phi)
        except ValueError:
            continue
        return PublicKey(n=n, e=e), PrivateKey(n=n, d=d), p, q


def _to_reference_public(pub: PublicKey):
    """Convert our PublicKey to a cryptography library RSAPublicKey object."""
    return RSAPublicNumbers(e=pub.e, n=pub.n).public_key()


def _to_reference_private(pub: PublicKey, priv: PrivateKey, p: int, q: int):
    """Convert our PrivateKey to a cryptography library RSAPrivateKey object."""
    pub_numbers = RSAPublicNumbers(e=pub.e, n=pub.n)
    return RSAPrivateNumbers(
        p=p,
        q=q,
        d=priv.d,
        dmp1=priv.d % (p - 1),
        dmq1=priv.d % (q - 1),
        iqmp=pow(q, -1, p),
        public_numbers=pub_numbers,
    ).private_key()


@pytest.fixture(scope="module")
def keypair():
    """Generate a 2048-bit keypair with factors shared across all tests in this module."""
    return _generate_keypair_with_factors(bits=2048)


# Direction 1: reference library encrypts, our impl decrypts

@pytest.mark.parametrize(
    "plaintext",
    [
        b"hello from cryptography",
        b"",
        b"x" * 190,  # max single OAEP-SHA256 block for 2048-bit
        b"\x00\x01\x02 binary \xff\xfe",
    ],
)
def test_reference_encrypt_our_decrypt(keypair, plaintext):
    """Verify that ciphertext produced by the reference library decrypts correctly with our implementation."""
    pub, priv, _, _ = keypair
    ref_pub = _to_reference_public(pub)
    ciphertext = ref_pub.encrypt(plaintext, OAEP_SHA256)
    assert len(ciphertext) == 256
    assert decrypt(ciphertext, priv) == plaintext


# Direction 2: our impl encrypts, reference library decrypts

@pytest.mark.parametrize(
    "plaintext",
    [
        b"hello from our impl",
        b"",
        b"x" * 190,
        b"\x00\x01\x02 binary \xff\xfe",
    ],
)
def test_our_encrypt_reference_decrypt(keypair, plaintext):
    """Verify that ciphertext produced by our implementation decrypts correctly with the reference library."""
    pub, priv, p, q = keypair
    ref_priv = _to_reference_private(pub, priv, p, q)
    ciphertext = encrypt(plaintext, pub)
    # For single-block plaintext, our ciphertext is exactly 256 bytes,
    # which is what the reference library's single-shot decrypt expects.
    assert len(ciphertext) == 256
    assert ref_priv.decrypt(ciphertext, OAEP_SHA256) == plaintext


# Sanity: the reference library accepts our generated keys at all
# (catches malformed n, e, d, p, q early)

def test_reference_library_accepts_our_keys(keypair):
    """Verify that the reference library can load keys generated by our implementation."""
    pub, priv, p, q = keypair
    ref_pub = _to_reference_public(pub)
    ref_priv = _to_reference_private(pub, priv, p, q)
    assert ref_pub.public_numbers().n == pub.n
    assert ref_pub.public_numbers().e == pub.e
    assert ref_priv.private_numbers().d == priv.d
    assert ref_priv.private_numbers().p * ref_priv.private_numbers().q == pub.n
